public class AppConstants {
	
    //Account Stage
	public static String ACCOUNT_STATUS_BLOCKED = 'Blocked';
    public static String ACCOUNT_STATUS_CANCELLED = 'Cancelled';
    
	//Opportunity Stage
    public Static String OPPORTUNITY_STAGE_CLOSED_LOST = 'Closed Lost';
    public Static String OPPORTUNITY_STAGE_CLOSED_WON = 'Closed Won';
    public Static String OPPORTUNITY_STAGE_Prospecting = 'Prospecting';
	public Static String OPPORTUNITY_STAGE_CANCELLED = 'Cancelled';
}