public Interface InterfaceExample {
    //To use an interface, another class must implement it by providing a body for all of the methods contained in the interface.
    /*
     * Interfaces can provide a layer of abstraction to your code. 
     * They separate the specific implementation of a method from the declaration for that method. 
     * This way you can have different implementations of a method based on your specific application.
     * 
     * */
     
    void meth1();
    void meth2();
}